services:
  - type: web
    name: silver-tree-website
    env: node
    rootDir: node-api-pagination-validation
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
